// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mpc/cluster.proto

package mpc

import (
	context "context"
	fmt "fmt"
	common "github.com/PaddlePaddle/PaddleDTX/dai/protos/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StepRequest wraps a message that is sent to a cluster member.
type StepRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*StepRequest_TrainRequest
	//	*StepRequest_PredictRequest
	Payload              isStepRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StepRequest) Reset()         { *m = StepRequest{} }
func (m *StepRequest) String() string { return proto.CompactTextString(m) }
func (*StepRequest) ProtoMessage()    {}
func (*StepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{0}
}

func (m *StepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepRequest.Unmarshal(m, b)
}
func (m *StepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepRequest.Marshal(b, m, deterministic)
}
func (m *StepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepRequest.Merge(m, src)
}
func (m *StepRequest) XXX_Size() int {
	return xxx_messageInfo_StepRequest.Size(m)
}
func (m *StepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepRequest proto.InternalMessageInfo

type isStepRequest_Payload interface {
	isStepRequest_Payload()
}

type StepRequest_TrainRequest struct {
	TrainRequest *TrainRequest `protobuf:"bytes,2,opt,name=train_request,json=trainRequest,proto3,oneof"`
}

type StepRequest_PredictRequest struct {
	PredictRequest *PredictRequest `protobuf:"bytes,3,opt,name=predict_request,json=predictRequest,proto3,oneof"`
}

func (*StepRequest_TrainRequest) isStepRequest_Payload() {}

func (*StepRequest_PredictRequest) isStepRequest_Payload() {}

func (m *StepRequest) GetPayload() isStepRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepRequest) GetTrainRequest() *TrainRequest {
	if x, ok := m.GetPayload().(*StepRequest_TrainRequest); ok {
		return x.TrainRequest
	}
	return nil
}

func (m *StepRequest) GetPredictRequest() *PredictRequest {
	if x, ok := m.GetPayload().(*StepRequest_PredictRequest); ok {
		return x.PredictRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepRequest_TrainRequest)(nil),
		(*StepRequest_PredictRequest)(nil),
	}
}

// StepResponse is a message received from a cluster member.
type StepResponse struct {
	// Types that are valid to be assigned to Payload:
	//	*StepResponse_TrainResponse
	//	*StepResponse_PredictResponse
	Payload              isStepResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StepResponse) Reset()         { *m = StepResponse{} }
func (m *StepResponse) String() string { return proto.CompactTextString(m) }
func (*StepResponse) ProtoMessage()    {}
func (*StepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{1}
}

func (m *StepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResponse.Unmarshal(m, b)
}
func (m *StepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResponse.Marshal(b, m, deterministic)
}
func (m *StepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResponse.Merge(m, src)
}
func (m *StepResponse) XXX_Size() int {
	return xxx_messageInfo_StepResponse.Size(m)
}
func (m *StepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepResponse proto.InternalMessageInfo

type isStepResponse_Payload interface {
	isStepResponse_Payload()
}

type StepResponse_TrainResponse struct {
	TrainResponse *TrainResponse `protobuf:"bytes,2,opt,name=train_response,json=trainResponse,proto3,oneof"`
}

type StepResponse_PredictResponse struct {
	PredictResponse *PredictResponse `protobuf:"bytes,3,opt,name=predict_response,json=predictResponse,proto3,oneof"`
}

func (*StepResponse_TrainResponse) isStepResponse_Payload() {}

func (*StepResponse_PredictResponse) isStepResponse_Payload() {}

func (m *StepResponse) GetPayload() isStepResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepResponse) GetTrainResponse() *TrainResponse {
	if x, ok := m.GetPayload().(*StepResponse_TrainResponse); ok {
		return x.TrainResponse
	}
	return nil
}

func (m *StepResponse) GetPredictResponse() *PredictResponse {
	if x, ok := m.GetPayload().(*StepResponse_PredictResponse); ok {
		return x.PredictResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepResponse_TrainResponse)(nil),
		(*StepResponse_PredictResponse)(nil),
	}
}

// TrainRequest is a message sent in training progress.
type TrainRequest struct {
	TaskID string           `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Algo   common.Algorithm `protobuf:"varint,3,opt,name=algo,proto3,enum=common.Algorithm" json:"algo,omitempty"`
	// payload can be processed by the specific algorithm
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainRequest) Reset()         { *m = TrainRequest{} }
func (m *TrainRequest) String() string { return proto.CompactTextString(m) }
func (*TrainRequest) ProtoMessage()    {}
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{2}
}

func (m *TrainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainRequest.Unmarshal(m, b)
}
func (m *TrainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainRequest.Marshal(b, m, deterministic)
}
func (m *TrainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainRequest.Merge(m, src)
}
func (m *TrainRequest) XXX_Size() int {
	return xxx_messageInfo_TrainRequest.Size(m)
}
func (m *TrainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrainRequest proto.InternalMessageInfo

func (m *TrainRequest) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *TrainRequest) GetAlgo() common.Algorithm {
	if m != nil {
		return m.Algo
	}
	return common.Algorithm_LINEAR_REGRESSION_VL
}

func (m *TrainRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// PredictRequest is a message sent in predicting progress.
type PredictRequest struct {
	TaskID               string           `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Algo                 common.Algorithm `protobuf:"varint,3,opt,name=algo,proto3,enum=common.Algorithm" json:"algo,omitempty"`
	Payload              []byte           `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PredictRequest) Reset()         { *m = PredictRequest{} }
func (m *PredictRequest) String() string { return proto.CompactTextString(m) }
func (*PredictRequest) ProtoMessage()    {}
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{3}
}

func (m *PredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictRequest.Unmarshal(m, b)
}
func (m *PredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictRequest.Marshal(b, m, deterministic)
}
func (m *PredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictRequest.Merge(m, src)
}
func (m *PredictRequest) XXX_Size() int {
	return xxx_messageInfo_PredictRequest.Size(m)
}
func (m *PredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictRequest proto.InternalMessageInfo

func (m *PredictRequest) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *PredictRequest) GetAlgo() common.Algorithm {
	if m != nil {
		return m.Algo
	}
	return common.Algorithm_LINEAR_REGRESSION_VL
}

func (m *PredictRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

//TrainResponse is a message responsed in training progress
type TrainResponse struct {
	TaskID string `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	// payload can be processed by the specific algorithm and training phase
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainResponse) Reset()         { *m = TrainResponse{} }
func (m *TrainResponse) String() string { return proto.CompactTextString(m) }
func (*TrainResponse) ProtoMessage()    {}
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{4}
}

func (m *TrainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainResponse.Unmarshal(m, b)
}
func (m *TrainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainResponse.Marshal(b, m, deterministic)
}
func (m *TrainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainResponse.Merge(m, src)
}
func (m *TrainResponse) XXX_Size() int {
	return xxx_messageInfo_TrainResponse.Size(m)
}
func (m *TrainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrainResponse proto.InternalMessageInfo

func (m *TrainResponse) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *TrainResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

//PredictResponse is a message responsed in predicting progress
type PredictResponse struct {
	TaskID string `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	// payload can be processed by the specific algorithm and predicting phase
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictResponse) Reset()         { *m = PredictResponse{} }
func (m *PredictResponse) String() string { return proto.CompactTextString(m) }
func (*PredictResponse) ProtoMessage()    {}
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aad46b65f84d4a0, []int{5}
}

func (m *PredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictResponse.Unmarshal(m, b)
}
func (m *PredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictResponse.Marshal(b, m, deterministic)
}
func (m *PredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictResponse.Merge(m, src)
}
func (m *PredictResponse) XXX_Size() int {
	return xxx_messageInfo_PredictResponse.Size(m)
}
func (m *PredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictResponse proto.InternalMessageInfo

func (m *PredictResponse) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *PredictResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*StepRequest)(nil), "mpc.StepRequest")
	proto.RegisterType((*StepResponse)(nil), "mpc.StepResponse")
	proto.RegisterType((*TrainRequest)(nil), "mpc.TrainRequest")
	proto.RegisterType((*PredictRequest)(nil), "mpc.PredictRequest")
	proto.RegisterType((*TrainResponse)(nil), "mpc.TrainResponse")
	proto.RegisterType((*PredictResponse)(nil), "mpc.PredictResponse")
}

func init() { proto.RegisterFile("mpc/cluster.proto", fileDescriptor_0aad46b65f84d4a0) }

var fileDescriptor_0aad46b65f84d4a0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x5e, 0xdd, 0xd8, 0xd8, 0x5b, 0xd7, 0xad, 0x99, 0xc8, 0xd8, 0x69, 0x0c, 0x84, 0x81, 0xd0,
	0x4a, 0x05, 0x11, 0x04, 0x61, 0x6e, 0x87, 0x79, 0x1b, 0x75, 0x07, 0xf1, 0x22, 0x5d, 0x1a, 0xba,
	0x62, 0xb3, 0xc4, 0x36, 0x3b, 0xf8, 0x37, 0xbc, 0xf9, 0x6f, 0x65, 0x49, 0xec, 0x52, 0xc1, 0x83,
	0x07, 0x2f, 0x6d, 0xdf, 0xf7, 0xfa, 0x7d, 0xef, 0xcb, 0x97, 0x07, 0x2e, 0xe5, 0xd8, 0xc7, 0xd9,
	0xbe, 0x10, 0x24, 0xf7, 0x78, 0xce, 0x04, 0x43, 0x75, 0xca, 0xf1, 0x68, 0x80, 0x19, 0xa5, 0x6c,
	0xe7, 0xab, 0x97, 0xea, 0x4c, 0x3e, 0x2c, 0xe8, 0x3c, 0x0a, 0xc2, 0x43, 0xf2, 0xb6, 0x27, 0x85,
	0x40, 0x37, 0xd0, 0x15, 0x79, 0x94, 0xee, 0x5e, 0x72, 0x05, 0x0c, 0x4f, 0xc6, 0xd6, 0xb4, 0x13,
	0xb8, 0x1e, 0xe5, 0xd8, 0x5b, 0x1f, 0x3a, 0xfa, 0xcf, 0x65, 0x2d, 0xb4, 0x85, 0x51, 0xa3, 0x3b,
	0xe8, 0xf1, 0x9c, 0xc4, 0x29, 0x16, 0x25, 0xb7, 0x2e, 0xb9, 0x03, 0xc9, 0x5d, 0xa9, 0xde, 0x91,
	0xed, 0xf0, 0x0a, 0x72, 0xdf, 0x86, 0x16, 0x8f, 0xde, 0x33, 0x16, 0xc5, 0x93, 0x4f, 0x0b, 0x6c,
	0x65, 0xaa, 0xe0, 0x6c, 0x57, 0x10, 0x74, 0x0b, 0xce, 0xb7, 0x2b, 0x85, 0x68, 0x5b, 0xc8, 0xb4,
	0xa5, 0x3a, 0xcb, 0x5a, 0xd8, 0x15, 0x26, 0x80, 0x66, 0xd0, 0x3f, 0x1a, 0xd3, 0x74, 0xe5, 0xec,
	0xb4, 0xea, 0xac, 0x14, 0xe8, 0xf1, 0x2a, 0x64, 0x7a, 0x4b, 0xc0, 0x36, 0x63, 0x40, 0x67, 0xd0,
	0x14, 0x51, 0xf1, 0xfa, 0xb0, 0x90, 0x96, 0xda, 0xa1, 0xae, 0xd0, 0x39, 0x34, 0xa2, 0x2c, 0x61,
	0x72, 0x92, 0x13, 0xb8, 0x9e, 0x4e, 0x7d, 0x96, 0x25, 0x2c, 0x4f, 0xc5, 0x96, 0x86, 0xb2, 0x8d,
	0x86, 0xa5, 0xf2, 0xb0, 0x31, 0xb6, 0xa6, 0x76, 0x58, 0x0e, 0x4a, 0xc1, 0xa9, 0x66, 0xf6, 0x7f,
	0xa3, 0x66, 0xd0, 0xad, 0x64, 0xf8, 0xeb, 0x24, 0x43, 0xa2, 0x5e, 0x95, 0x98, 0x43, 0xef, 0x47,
	0x8e, 0x7f, 0x17, 0x09, 0xae, 0xa1, 0x35, 0x57, 0x7b, 0x8b, 0x2e, 0xa0, 0x71, 0xd8, 0x00, 0xd4,
	0x97, 0x57, 0x64, 0x6c, 0xe8, 0xc8, 0x35, 0x10, 0x7d, 0x3d, 0xc1, 0xf3, 0x65, 0x92, 0x8a, 0xed,
	0x7e, 0x73, 0x38, 0xba, 0xbf, 0x8a, 0xe2, 0x38, 0x23, 0xea, 0xa9, 0x8b, 0xc5, 0xfa, 0xc9, 0x8f,
	0xa3, 0xd4, 0x97, 0x3b, 0x5f, 0xf8, 0x94, 0xe3, 0x4d, 0x53, 0x7e, 0x5f, 0x7d, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0xe9, 0x7e, 0x01, 0x2e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, "/mpc.Cluster/Step", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(context.Context, *StepRequest) (*StepResponse, error)
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (*UnimplementedClusterServer) Step(ctx context.Context, req *StepRequest) (*StepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.Cluster/Step",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Step",
			Handler:    _Cluster_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc/cluster.proto",
}
